### ISSUE TITLE
source poky building .... command not found

### ISSUE THREAD

**Issue by mrsalhaoui** [siemens/meta-iot2000#115]
Hello,

I have finished the Kas method with adding layers and packages, but when I try to make the source command it fails, any Help please ? 

![image](https://user-images.githubusercontent.com/33464198/52621916-ca9a3d00-2ea8-11e9-891b-f8d46505d88c.png)

**Comment by jan-kiszka** [comment]
The kas build included that step already -  you are done with building! Just follow the README regarding  image writing.

**Comment by mrsalhaoui** [comment]
but I have added  some layers amd packages after the Kas command : 
This is explaned by Bergmanu in this post : 

https://support.industry.siemens.com/tf/ww/en/posts/modifying-the-sd-card-image-adding-new-layers/177554/?page=0&pageSize=10

**Comment by jan-kiszka** [comment]
Please follow the more recent description in https://support.industry.siemens.com/tf/ww/en/posts/creating-custom-layer/182600/?page=0&pageSize=10. There is even in skeleton layer for customizations available for download.

In a nutshell: If you use kas as management tool for the build, you should stay in that world. If you use bitbake, you first need to replicate the layer setup that kas describes and creates for you, then you can call the setup script and start bitbake. That's a different workflow.

**Comment by mrsalhaoui** [comment]
It is not very clear, I will try too understand how it works again...!
But the changes that I have made after the kas command I have to delete them or not ?

**Comment by jan-kiszka** [comment]
Yeah, that thread and the reference layer may lack some words if you aren't familiar with yocto yet.

The idea of the layer is to move you customizations in form of overlays and additional recipes into a separate repository. That allows to update meta-iot2000 without rewriting your changes or maintaining a fork of that layer. That's a typical yocto pattern.

Of course, you can also create branch in your meta-iot2000 clone, adjust what you would like to do differently or in addition, check that in and build the whole image as if you are building it unmodified from scratch. But then, when you want to use a newer version of meta-iot200 in the future, you will have to rebase your changes on top.

**Comment by mrsalhaoui** [comment]
Here is my situation now : 
 I made the 3 next steps in the home folder : 
1.  install the packages required by yocto here https://www.yoctoproject.org/docs/2.2/mega-manual/mega-manual.html#packages 
2. pip3 install kas
3.  git clone https://github.com/siemens/meta-iot2000
4. kas build meta-iot2000/meta-iot2000-example/kas.yml


then I have the home folder as shown  in the image : 

![image](https://user-images.githubusercontent.com/33464198/52733498-2c4eca00-2fc3-11e9-8f87-f018ad230de4.png)

If I want to add this recipe  https://layers.openembedded.org/layerindex/recipe/47350/ which is in the openembedded-core Layer,  what should I do ? I have to clone a new layer in the home folder ? or just modify the tiny customization layer that jan-k proposed in this link 

https://support.industry.siemens.com/tf/ww/en/posts/creating-custom-layer/182600/?page=0&pageSize=10 ? 

Could you please describe to me clearly the changes that I have to do in order add this recipe before passing to the next steps ( source builb... and bitbake)

**Comment by jan-kiszka** [comment]
The fastest solution to get to an image with only this additional package is indeed

- add ```IMAGE_INSTALL_append = " ffmpeg"``` to meta-iot2000/meta-iot2000-example/recipes-core/images/iot2000-example-image.inc
- run ```kas build meta-iot2000/meta-iot2000-example/kas.yml``` once again

Maintaining this little customization by re-adding this line to each newer version of our layer before bulding is fine.

**Comment by mrsalhaoui** [comment]
After Making these Steps now, it appears another errors : 

* install the packages required by yocto here https://www.yoctoproject.org/docs/2.2/mega-manual/mega-manual.html#packages
* pip3 install kas
* git clone https://github.com/siemens/meta-iot2000
* kas build meta-iot2000/meta-iot2000-example/kas.yml
* add `IMAGE_INSTALL_append = " ffmpeg"` to meta-iot2000/meta-iot2000-example/recipes-core/images/iot2000-example-image.inc
* run `kas build meta-iot2000/meta-iot2000-example/kas.yml` once again

![image](https://user-images.githubusercontent.com/33464198/52806422-481ca380-3089-11e9-81b6-5583f950fa7e.png)
![image](https://user-images.githubusercontent.com/33464198/52806443-59fe4680-3089-11e9-8b2f-3dc7ff75bef1.png)

**Comment by jan-kiszka** [comment]
OK, there is another trick needed: add ```LICENSE_FLAGS_WHITELIST += " commercial"``` to, e.g., meta-iot2000/meta-iot2000-example/conf/distro/poky-iot2000.conf.

**Comment by mrsalhaoui** [comment]
Thank you Jan, 

The steps done until now  in order to enable ffmpeg are : 

* install the packages required by yocto here https://www.yoctoproject.org/docs/2.2/mega-manual/mega-manual.html#packages
* pip3 install kas
* git clone https://github.com/siemens/meta-iot2000
* kas build meta-iot2000/meta-iot2000-example/kas.yml
* add `IMAGE_INSTALL_append = " ffmpeg"` to meta-iot2000/meta-iot2000-example/recipes-core/images/iot2000-example-image.inc
add `LICENSE_FLAGS_WHITELIST += "commercial"` to, e.g., meta-iot2000/meta-iot2000-example/conf/distro/poky-iot2000.conf
* run `kas build meta-iot2000/meta-iot2000-example/kas.yml` once again

The result  after making the last command twice is : 

![image](https://user-images.githubusercontent.com/33464198/52850879-f0c41500-3114-11e9-9662-6fdb1351a28b.png)

so now I don't need to use the source command and bitbake right ?  I have just to copy the image to the SD card using this command and test if the package ffmpeg works in the IoT gateway ?

* sudo dd if=build/tmp/deploy/images/iot2000/iot2000-example-image-iot2000.wic \
          of=/dev/mmcblk0 bs=4M oflag=sync

**Comment by jan-kiszka** [comment]
Yes, it's exactly that easy now!

**Comment by mrsalhaoui** [comment]
I want now to boot from an USB SD card reader, 
![image](https://user-images.githubusercontent.com/33464198/52856361-7a2f1380-3124-11e9-9d81-28b84455f7ee.png)
 but don't find the folder loader/entries, where can I find it ? what should I do to modify it to accept the boot from sdb/sdb1 as shown in the Picture.

**Comment by mrsalhaoui** [comment]
Is It fine like that in Ubuntu ? 

![image](https://user-images.githubusercontent.com/33464198/52857884-d09e5100-3128-11e9-90b0-c62d4f263498.png)

**Comment by jan-kiszka** [comment]
Not quite: Assuming that /dev/sdb is the SD card in your reader (you should check by validating that there is no /dev/sdb* when there is no reader), you should dump to the whole disk, ie. to /dev/sdb directly.

**Comment by mrsalhaoui** [comment]
I have just zipped the .wic file and I writed the image on the SD card using windows, I can access now to the IoT gateway using SSH, but still the FFMPEG not working, I don't really know why ? is there another way to make it working, I really need it ..

Error: Ffmpeg exited with error code: null

**Comment by jan-kiszka** [comment]
It may get way more complicated now: We are running on CPU here that is architecturally a Pentium I and has no SSE* accelerator instructions. Many modern x86 software use these instructions intensively, either by asking the compiler to inject them where reasonable - this is what we avoid when building applications via Yocto for the IOT2000 - or by using own assembly directly. The latter is not that easy to prevent. Sometimes it takes special configuration of the application build steps to activate a fallback, but often these fallbacks are not implemented any more. And sometimes they exist but became broken.

You could try running ffmpeg inside gdb on the target, to check if some illegal instruction or other exception occurs.

**Comment by mrsalhaoui** [comment]
I have really no idea how to make that, any suggestions, please ..
I'm using a Nodejs application

**Comment by jan-kiszka** [comment]
So, some nodejs script is triggering the invocation of ffmpeg? Or what are your steps to trigger that error message?

**Comment by mrsalhaoui** [comment]
I'm using a drone library in Github, the error came from the PngEncoder.js file, please see the link below : 

https://github.com/felixge/node-ar-drone/blob/master/lib/video/PngEncoder.js

**Comment by jan-kiszka** [comment]
OK... So would have to extract the command line of the ffmpeg call (all parameters) from the that script, call ```gdb --args ffmpeg ..```, then tell gdb to ```run``` the program. When it crashed, issue ```bt``` and ```disassemble $pc,+10``` inside gdb. That may give us some idea what goes wrong. Not yet how to solve it, though.

**Comment by mrsalhaoui** [comment]
1- Do You mean that I have to extract the command line of that error from the PngEncoder.js File ? or all the command lines of errors ? 

2- I have called the " gdb --args ffmpeg PngEncoder.js " inside the video Folder that contains the PngEncoder.js File and the errors ? is that right, ? because I use other file in another folder to start the application and commincate with the drone ? which is https://github.com/felixge/node-ar-drone/blob/master/examples/png-stream.js

Here you find some results of " gdb --args ffmpeg PngEncoder.js "

![image](https://user-images.githubusercontent.com/33464198/53008511-daca9300-3439-11e9-9848-a943b9a69455.png)

**Comment by jan-kiszka** [comment]
You need to find out, which options PngEncoder.js passes to ffmpeg when the problem occurs. That you need to feed into the gdb command I sketched.

**Comment by mrsalhaoui** [comment]
Hello Again Jan,

I have contacted the person who made the code, and we tried to know what happend with FFMPEG : 

after changing a little bit the code, we found that type of the error : 

the error was SIGILL,  

"" means that FFMPEG has probably been compiled incorrectly. I.e. the binary contains a CPU instruction that isn't available on the CPU you're trying to execute this on.""

What do you think about that Jan ?

**Comment by jan-kiszka** [comment]
This give a reasonable explanation for the crash, not yet for how the instruction(s) got into the binary. There are at least two options
- the recipe to build ffmpeg injects own switches that allow unsupported instructions
- the code contains inline assembly with such instructions

To get a clue about that, it would be good to have a backtrace to the instructions causing the SIGILL. Maybe your contact can help you with operating gdb in the required way - and also with interpreting the result. If it is a recipe issue, that can likely be fixed. Inline assembly would be tricky.

**Comment by mrsalhaoui** [comment]
My contact said that I can debug/reproduce this by copying some h264 encoded video to this computer and trying to use FFMPEG to convert it into something else, 

I have tried to do that in the IOT gatway by using this command "ffmpeg -i video.flv image%d.jpg" to convert a video to images and it is working as you can see in the image,
![image](https://user-images.githubusercontent.com/33464198/53904154-b4197880-4045-11e9-9f4d-4afa968d0e66.png)

About the debugger I don't really know how to use it yet,

**Comment by jan-kiszka** [comment]
You still need to find out how exactly ffmpeg is called in your scenario. Depending on the selection mode, different code paths will be taken, and the case above may not trigger the corresponding ones. Check your original js file again. There is PngEncoder.prototype._spawnFfmpeg which assembles the command line of ffmpeg. Extract that, e.g. by printing ffmpegOptions, and try to reproduce the crash. Then we can discuss gdb usage again.

**Comment by mrsalhaoui** [comment]
I tried as you proposed to print the ffmpegOptions in the PngEncoder.prototype._spawnFfmpeg function  : as you can see in the code below : 

PngEncoder.prototype._spawnFfmpeg = function() {
  var ffmpegOptions = [];
  ffmpegOptions.push('-i', '-'); 

  console.log("extraction-1",ffmpegOptions); // input flag

  ffmpegOptions.push('-f', 'image2pipe');

   console.log("extraction-2",ffmpegOptions);// format flag

  if(this._imageSize){
    ffmpegOptions.push('-s', this._imageSize);
    console.log("extraction-3",ffmpegOptions); // size flag
  }
  ffmpegOptions.push('-vcodec', 'png'); 

  console.log("extraction-4",ffmpegOptions);// codec flag

  ffmpegOptions.push('-r', this._frameRate);

  console.log("extraction-5",ffmpegOptions); // framerate flag

  ffmpegOptions.push('-');
   console.log("extraction-6",ffmpegOptions) // output

  // @TODO allow people to configure the ffmpeg path

  return this._spawn('ffmpeg', ffmpegOptions);

  console.log("extraction-7",ffmpegOptions);

};
 then I got these outputs after reproducing the same crash : 

![image](https://user-images.githubusercontent.com/33464198/54289714-eed16280-45a9-11e9-8be7-8d4379cf03a5.png)

**Comment by jan-kiszka** [comment]
Do you have a .png file at hand? I think this should reproduce the crash as well:
```
ffmpeg -i some.png -f image2pipe -vcodec png -r 5 output.file
```
If yes, run that under gdb:
```
gdb --args ffmpeg ...
```

**Comment by mrsalhaoui** [comment]
I think it works fine, no crash detected 

![image](https://user-images.githubusercontent.com/33464198/54358259-2dc1ef80-4660-11e9-9a55-e9739b12fa03.png)

**Comment by jan-kiszka** [comment]
If you look at the last line, you should see something familiar...

**Comment by mrsalhaoui** [comment]
Illegal instruction ? What is that ?

**Comment by jan-kiszka** [comment]
The same type of error message you js file was triggering as well.
So, now attach gdb to that ffmpeg call.

**Comment by mrsalhaoui** [comment]
Here we can see it also after runing gdb 

![image](https://user-images.githubusercontent.com/33464198/54358901-bab97880-4661-11e9-85e7-3b817f34eefa.png)

**Comment by jan-kiszka** [comment]
> OK... So would have to extract the command line of the ffmpeg call (all parameters) from the that script, call `gdb --args ffmpeg ..`, then tell gdb to `run` the program. When it crashed, issue `bt` and `disassemble $pc,+10` inside gdb. That may give us some idea what goes wrong. Not yet how to solve it, though.

This is what I was refererring to.

**Comment by mrsalhaoui** [comment]
After an issue of _bt_ and _disassemble $pc,+10_, I have got : 

![image](https://user-images.githubusercontent.com/33464198/54359210-7aa6c580-4662-11e9-9420-309bfab0b0a9.png)

**Comment by mrsalhaoui** [comment]
What do you think Jan ?

**Comment by jan-kiszka** [comment]
cmov is an unsupported instruction for the target CPU. I'm trying to rebuild the recipe to check why it was used by ffmpeg. But my environment is already some versions ahead, may not give identical results.

Could you attach (no screenshots, please) the log file from the build similar to ```build/tmp/work/i586-nlp-32-poky-linux/ffmpeg/3.3.3-r0/temp/log.do_configure```?

**Comment by mrsalhaoui** [comment]
Please find attached the file 



[log.txt](https://github.com/siemens/meta-iot2000/files/2966789/log.txt)

**Comment by jan-kiszka** [comment]
Yeah, that's in line with what I see. Here is a quick-fix/hack:

Create ```meta-iot2000-bsp/recipes-multimedia/ffmpeg/ffmpeg_%.bbappend``` with this content:
```
def cpu(d):
    return "i586"
```

Then rebuild. The log.do_configure should then show that MMX, SSE, i686 features etc. are all disabled, and the crash should be gone.

**Comment by mrsalhaoui** [comment]
There is no meta-iot2000-bsp, I have just meta-iot2000 in my machine ?

**Comment by jan-kiszka** [comment]
```mkdir -p meta-iot2000/meta-iot2000-bsp/recipes-multimedia/ffmpeg```, then create that file.

**Comment by mrsalhaoui** [comment]
ok the file is created, so do you mean I have to type the Kas command again right : 

kas build meta-iot2000/meta-iot2000-example/kas.yml

**Comment by jan-kiszka** [comment]
Yes, that should trigger the rebuild of ffmpeg (you will see that) and the re-assembly of the image.

**Comment by mrsalhaoui** [comment]
Ok Thank you Jan, I'm making it now, I will write this new image in the SD card and tell you if the application works fine.

**Comment by mrsalhaoui** [comment]
All of this was to make ffmpeg working perfectly in Siemens IOT2040 for this application,

Thank you so much Jan, I can see now the pictures from the drone

![image](https://user-images.githubusercontent.com/33464198/54433133-68dd2500-472b-11e9-8b27-ba434147be93.png)

**Comment by jan-kiszka** [comment]
Hey, cool! Congrats!

I will add at least that ffmpeg recipe artifact to the bsp layer, for future releases.
