### ISSUE TITLE
Use Com Port

### ISSUE THREAD

**Issue by Nick135** [siemens/meta-iot2000#116]
I will use the Com Port (RS232/RS485) to connect to S7 MPI from C# (Mono)
How can I use/adress the com port of the IOT2040?

**Comment by jan-kiszka** [comment]
This question is better handled in the customer support forum at https://support.industry.siemens.com/tf/ww/en/threads/303/?page=0&pageSize=10 as it is not specific to this Yocto layer. Could you repost there?
