### ISSUE TITLE
Can you publish a standard image?

### ISSUE THREAD

**Issue by cooldk** [siemens/meta-iot2000#127]
Since you publish an image which is 2.2.0 at https://support.industry.siemens.com/cs/document/109741799/simatic-iot2000-sd-card-example-image?dti=0&lc=en-US
in 04/13/2018. Can you guys publish a new standard image which is the lastest version?

**Comment by jan-kiszka** [comment]
Yeah, sorry. I heard that there were technical issues while publishing 2.4.0. Hopefully resolved soon.

**Comment by jan-kiszka** [comment]
Version 2.4.0 is now available for download.
