### ISSUE TITLE
kas build meta-iot2000-bsp/kas.yml issue

### ISSUE THREAD

**Issue by telimen** [siemens/meta-iot2000#128]
Hi!
I am trying to build the bsp image but I keep getting errors. I get the message "Config file validation Error: None is not of type 'object'"
I have successfully built the image before so this is a new error for me.
Thankful for any advice.

Kind regards 
Henrik Olsson

**Comment by telimen** [comment]
I also got the error "No such file or directory: '/home/henrik/meta-iot2000-bsp/kas.yml' "
When I created the file I got the first error found above.

**Comment by jan-kiszka** [comment]
Are you building from master? What is the command line you used? What is your kas version?

**Comment by telimen** [comment]
Thank you for the quick response! I am building from master I believe. Just followed the guide that is here on the native build. I think kas is the latest version.
It is when I try "kas build..." with the bsp version.

**Comment by jan-kiszka** [comment]
We've changed things in master /wrt kas recently, so maybe something is still out of sync.

So you are on 27c1e810148b92d4c3ddea9c0ad49a11e9561878? You called `kas build meta-iot2000/kas-bsp.yml` (that part changed, compared to older versions)?

**Comment by telimen** [comment]
Yes, it worked fine a couple of weeks ago. Is this something that is planned to get fixed?

**Comment by jan-kiszka** [comment]
If you are using the line I cited above, ie. '.../kas-bsp.yml' rather than '.../meta-iot2000-bsp/kas.yml', this is working. It's part of our CI, and I also just tried that again locally. So, please double-check what you are actually calling.

**Comment by telimen** [comment]
Ok, thanks, I'll try again.

**Comment by telimen** [comment]
Now it worked fine, weird. But anyway, I was hoping to use something else instead of Docker. Is there a decent option or do I just follow your guide?

**Comment by jan-kiszka** [comment]
Native build is still an option. Just ensure that your host Linux fulfills the Yocto build requirements (link is in the README - just needs a version update) and then call "kas build" directly.

**Comment by telimen** [comment]
Ok, thanks, I'll try it out.

**Comment by telimen** [comment]
I get through the native build OK, but Docker isn't working for me.  The command that is failing is:
$ docker run -v $(pwd):/shared-volume:rw -e USER_ID=$(id -u) --rm -t -i \
             --storage-opt size=50G kasproject/kas:latest sh -c "
      cd /shared-volume &&
      git clone https://github.com/siemens/meta-iot2000 &&
      kas build meta-iot2000/kas-example.yml"

I get the error message "docker: Error response from daemon: --storage-opt is not supported for overlay."

The same happens when I use overlay2. And the same when I try using the kas-bsp.yml.

**Comment by telimen** [comment]
Of course, I would be happy to not use Docker at all. But how do I use the native build? All I have is the yml-file or how can I put it on the IOT2000?

**Comment by jan-kiszka** [comment]
I don't get it: You said you got through the native build, no? Then why would you still also apply the docker build?

Regarding docker: --storage-opt is indeed no longer needed for recent distro configurations of docker. We also do not have it as part of kas-docker (https://github.com/siemens/kas/blob/master/kas-docker). So I guess it's time to adjust our description here, switching to kas-docker.

**Comment by telimen** [comment]
Oh, my bad. I didn't fully understand how to proceed after doing the native build. What do I do after building with kas? Is it good to go? How do I get Yocto onto my IOT2000?

**Comment by jan-kiszka** [comment]
https://github.com/siemens/meta-iot2000#booting-the-image-from-sd-card

**Comment by telimen** [comment]
And it also works for the bsp-image? Thanks a lot, really helps!

**Comment by jan-kiszka** [comment]
The pattern, yet. But you need to adjust the path to the image file.

**Comment by telimen** [comment]
Ok, I will try that.

**Comment by telimen** [comment]
I saw that the example image on Siemens' web page had been updated so I'll use that one instead. It installed properly and now it's time to get the 4G-modem PCIE-card to work. Thank you again for all your help.
