### ISSUE TITLE
Add new node-red node

### ISSUE THREAD

**Issue by applea9** [siemens/meta-iot2000#139]
Hello,

I am trying to add node-red-contrib-s7 node in the image, could you give some information about how to get npm-shrinkwrap.json file for node-red-contrib-s7?

thanks a lot!

**Comment by jan-kiszka** [comment]
Sure, that info is hidden here: https://github.com/siemens/meta-iot2000/blob/master/meta-iot2000-example/classes/npm-ng.bbclass#L5

**Comment by applea9** [comment]
Thanks.
