### ISSUE TITLE
python-error after building example image 

### ISSUE THREAD

**Issue by IoTcreator** [siemens/meta-iot2000#140]
Hello guys, 
after i typed in an executed the command `kas build meta-iot2000/kas-example.yml` to build the example image i get the errror:

> TypeError: signal handler must be signal.SIG_IGN, signal SIG_DFL, or a callable object. 
![error_Python_kas](https://user-images.githubusercontent.com/57444228/68300941-204def80-009f-11ea-9017-98517677b957.PNG)

I searched nearly every forum that i can find about that issue but no solution is working for me so far. 
I hope u can help out. 
Thanks in advance!
Best regards! 

[ Im using an IoT2040 with an Linux Yocto image on it, provided by siemens. Example-image: https://support.industry.siemens.com/cs/document/109741799/simatic-iot2000-sd-card-example-image?dti=0&lc=en-WW ]

**Comment by jan-kiszka** [comment]
See https://support.industry.siemens.com/tf/ww/en/posts/python-error-on-trying-to-build-own-image/223168/?page=0&pageSize=10. And I also suspect that the first error (always read from the start, not the end, when parsing errors) is different. Eg. there is no git.
