### ISSUE TITLE
Replace node-red-contrib-iiot-opcua with node-red-contrib-opcua 

### ISSUE THREAD

**Issue by bergmanu** [siemens/meta-iot2000#160]
Maybe we should refrain from providing the _node-red-contrib-iiot-opcua_ preinstalled, since this node is now [deprecated ](https://www.npmjs.com/package/node-red-contrib-iiot-opcua)and moved to a non-free solution?

**Comment by applea9** [comment]
How about to replace with node-red-contrib-opcua?

**Comment by jan-kiszka** [comment]
Yes, we do the same for meta-iot2050 already. Updated the subject accordingly.

**Comment by BaochengSu** [comment]
f366c1ea668b8f4f7d09dc7659e939d59346a3a6 has fixed this issue, so close it.
