### ISSUE TITLE
Not possible to install nodes with V3.1.1

### ISSUE THREAD

**Issue by bergmanu** [siemens/meta-iot2000#175]
Since some time it is not possible any more to install any node with the Example Image V3.1.1. 
No matter which node is installed this error appears: 
![node-red](https://user-images.githubusercontent.com/22653568/154698111-56ae59b6-a819-4149-b035-60d2e2463b73.png)

I tried to update fsevents, which fails with this error: 
![update-fsevents](https://user-images.githubusercontent.com/22653568/154698342-9ec7c9bb-9e35-4206-b5ae-10eb68888b03.png)

Do you know a way to solve this?

**Comment by jan-kiszka** [comment]
Looks as if that fsevents package got broken upstream - if it only wants to work on Mac.

**Comment by jan-kiszka** [comment]
https://www.npmjs.com/package/fsevents - this is for MacOS only. Question is why it is pulled then... No idea, but it looks messy.

**Comment by bergmanu** [comment]
Oh right, didn't recognize the MAC thing.

**Comment by bergmanu** [comment]
I did some further tests. Seems that installing node globally (-g) works, but installing via Manage Palette doesn't work. 

Test steps with s7 node: 
- npm install -g node-red-contrib-s7@2.1.1 --> works
- Update node-red-contrib-s7 to V3.0 via Manage Palette --> fails with fsevents error
- npm install -g node-red-contrib-s7 --> works and installs version 3.1
- npm install -g node-red-contrib-s7@3.0 --> works

Test steps with bit node: 
- Install node-red-contrb-bit via Manage Palette --> fails with fsevents error
- npm install -g node-red-contrib-bit --> works

Test steps with config node: 
- Install node-red-contrb-config via Manage Palette --> no response
- npm install -g node-red-contrib-config--> works
