### ISSUE TITLE
Suggestion: NTP Client as IoT2020 has no battery backup.

### ISSUE THREAD

**Issue by DanPlastina** [siemens/meta-iot2000#24]
It would be fantastic if an NTP client was added to facilitate setting the clock on power up.

**Comment by nospam2000** [comment]
Adding ntpd will be one of my first projects for a self-baked image.

Hopefully I can get it working as stratum 1 server with a locally connected GPS receiver and even with PPS, but this depends on the hardware and kernel drivers.

**Comment by jan-kiszka** [comment]
Busybox has a built-in service for this, we just lack its activation. But we are taking patches 😉.

**Comment by nospam2000** [comment]
BusyBox's ntp client is small, but also has limitations. A short look at its [REAME](http://doolittle.icarus.com/ntpclient/README) says for example that is doesn't support multiple servers.
ntpd is not only an ntp client but also a ntp server.

Nevertheless BusyBox will be appropriate for many users.

**Comment by jan-kiszka** [comment]
Hmm, the code says the busybox client supports multiple servers. It also has an optional server mode as well, but I have no own experience to compare it to a full-blown one.

**Comment by nospam2000** [comment]
I have now ntpd running using the standard recipe from OpenEmbedded and an adapted config file. Do you want a patch or merge request or a description how to get it into the image?

**Comment by jan-kiszka** [comment]
Pull request, please. Regarding the style of the commit, follow other commits in this repo. The log should describe why we want this change and carry a signed-off according to https://developercertificate.org.

I would suggest to preconfigure things generically for ntpclient operation, using e.g. the parameters of http://www.pool.ntp.org/en/use.html.

Did you also try the busybox applet? In any case, please document the reason for choosing the full-featured one.

**Comment by nospam2000** [comment]
sorry, I won't submit a pull request, because I quit using yocto and switch to debian.

**Comment by jan-kiszka** [comment]
...at your own risk.
You will have to rebuild an undefined number of packages then (I think I cited a war story elsewhere). An own kernel will also be required unless you can even live without network (will improve with 4.12 and then significantly with 4.13).
If you want to do this properly, this can be an interesting tool to describe the process: https://github.com/ilbers/isar. We didn't follow this path for the IOT2000 due to the significant effort + the fact that users will still not be able to pull from arbitrary Debian repos.

**Comment by jan-kiszka** [comment]
Feature merged - thanks for the suggestion and inputs.
