### ISSUE TITLE
Integrate in-field image update support

### ISSUE THREAD

**Issue by jan-kiszka** [siemens/meta-iot2000#39]
The bits and pieces for a software update mechanism for IOT2000 devices is work in progress. It would be useful to integrate this feature in form of a reference implementation into meta-iot2000 once the missing pieces are done and published.

**Comment by jan-kiszka** [comment]
Building blocks:
- https://github.com/siemens/meta-efibootguard
- https://github.com/sbabic/meta-swupdate

**Comment by nuno407** [comment]
Hi @jan-kiszka ,
Any update regarding this issue?
Thank you, Nuno

**Comment by jan-kiszka** [comment]
Not forgotten but unfortunately postponed due to resource scheduling issues. I just brought up the topic internally again.

**Comment by nuno407** [comment]
Hi @jan-kiszka,
Thank you for the fast response. I think this is a major feature.
How can I help in order to accomplish it?

**Comment by jan-kiszka** [comment]
@nuno407 Thanks a lot. However, the immediate to-dos at this point are hard to break down, but we would come back to you for testing: I'm optimistic that we can pick this up again in couple of weeks.

**Comment by jan-kiszka** [comment]
Merged into master now.
