### ISSUE TITLE
Image size parameters don't work

### ISSUE THREAD

**Issue by yetkinozturk** [siemens/meta-iot2000#45]
Hello,
I have tried IMAGE_ROOTFS_SIZE and IMAGE_ROOTFS_EXTRA_SPACE variables in local.conf but the wic image size didn't change.  Other images are resized as expected.

**Comment by jan-kiszka** [comment]
It does work: if you check the rootfs artifacts, they contain zeros at the end. Those are not part of the wic image, they are cut off. Try flashing and booting - but note that the example image will expand to the full disk size during boot automatically. If you disable this or switch to the pure bsp layer, the effect should be visible.
