### ISSUE TITLE
iot2000setup Excute Error

### ISSUE THREAD

**Issue by hhdang** [siemens/meta-iot2000#49]
ImportError: No module named snack
--------------------------------------------------
root@iot2000:~# iot2000setup
Traceback (most recent call last):
  File "/usr/bin/iot2000setup", line 4, in <module>
    from snack import *
ImportError: No module named snack

root@iot2000:/etc# cat image-release
IMAGE_RELEASE="V2.1.3"
root@iot2000:/etc# uname -a
Linux iot2000 4.4.60-yocto-standard #1 PREEMPT Sat Jun 17 00:49:42 CST 2017 i586 i586 i386 GNU/Linux

**Comment by jan-kiszka** [comment]
Yep, already addressed by #48 - time to merge...
