### ISSUE TITLE
bitbake fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by jcgruenhage** [siemens/meta-iot2000#52]
I just tried to build the meta-iot2000-bsp image on Ubuntu 17.04, exactly like specified in the README, and it fails with this error message:

![error](https://user-images.githubusercontent.com/6861958/28410053-c5cf2c24-6d3c-11e7-9d29-8d460e5267e4.png)

I also wanted to add that all of the tested distros listed on the README page are out of date, except OpenSuse 42.2, which will go out of date in less than a week. I'll test it with Debian 9 now, hopefully that will work.

**Comment by jan-kiszka** [comment]
The REAME in master is likely out of date and will be replaced soon with what is in jan/staging. Specifically the Docker way can be interesting if you face compatibility/dependency issues with your Distro (and will replace that list of tested distros).

**Comment by jcgruenhage** [comment]
Oh, I hadn't even noticed the other branches.. I'll check out the docker build, thank you :)

**Comment by jcgruenhage** [comment]
So, the docker build has worked mostly fine, but there is one thing that didn't quite work. Why is the user set to `id -u` in the container? Docker commands are usually run as root [(comment by RedHat why this should stay that way)](https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/), which causes the image to not run, because on startup it then complains, that it can't create a the root user because that already exists.

**Comment by jan-kiszka** [comment]
Other distros are less strict, so things were modeled around them so far. But we should fix the image invocation as root in that container, ie. in [kas](https://github.com/siemens/kas). Thanks for the note!

**Comment by jan-kiszka** [comment]
Patch for kas was sent upstream. So the Docker issue you reported will be addressed when we use the next version of kas (I'm waiting for it to merge a properly adjusted README).
