### ISSUE TITLE
kas-sdk-linux-x64.yml version not compatible with README.md examples

### ISSUE THREAD

**Issue by DaCookie4u** [siemens/meta-iot2000#70]
I noticed that the kas command described in README.md for building the SDK is not compatible with the docker build command inside the README.md:

```
docker run -v (pwd):/shared-volume:rw -e USER_ID=(id -u) --rm -t -i \
              kasproject/kas:0.11.0 sh -c "
              cd /shared-volume &&
              git clone https://github.com/siemens/meta-iot2000 &&
              kas build meta-iot2000/meta-iot2000-example/kas-sdk-linux-x64.yml"
```

`kas.includehandler.LoadConfigException: This version of kas is compatible with version 1 to 2, file has version 3: /shared-volume/meta-iot2000/meta-iot2000-example/kas-sdk-linux-x64.yml`

Not sure if that is intended. Changing either the file to version 2, or using the latest kasproject/kas image solves the problem. Although I did not take the time to check whether build successfully completes with the latest docker image. I went for the first solution.

**Comment by jan-kiszka** [comment]
The first workaround is not the right one. We need to update the link, likely just removing the specific version reference, suggesting latest. Thanks for the note!

**Comment by DaCookie4u** [comment]
Yes I just noticed :) I ran a second run with the latest kas image and now I have a working sdk script. Thanks for the info. Correct docker run for SDK would be:

```
docker run -v "$VOLUME":/shared-volume:rw -e USER_ID=$(id -u) --rm -t -i \
              kasproject/kas sh -c "
                cd /shared-volume &&
                git clone https://github.com/siemens/meta-iot2000 &&
                kas build meta-iot2000/meta-iot2000-example/kas-sdk-linux-x64.yml"
```

**Comment by jan-kiszka** [comment]
Fixed in master.
